#TODO env variables

EXIASAVER_HOME=~/ExiaSaver/

EXIASAVER1_PBM=~/ExiaSaver/PBM/

EXIASAVER2_PBM=~/ExiaSaver/PBM/

EXIASAVER2_TAILLE=5x3

EXIASAVER2_SLEEP=2

EXIASAVER3_PBM=~/ExiaSaver/PBM/